[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
  included_files = ["netlify/functions-src/**/*"]

[dev]
  functions = "netlify/functions"
  functionsPort = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/functions/stripe-webhook"
  status = 200
  force = true
  conditions = {Content-Type = "application/json"}

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_STRIPE_PUBLIC_KEY,VITE_*,STRIPE_SECRET_KEY"
  SECRETS_SCAN_OMIT_PATHS = "/dist/*,/build/*,/supabase/functions/create-checkout-session/.env"

[build.processing]
  skip_processing = false